name: Deploy LemonBot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Bot
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          cd $LEMONBOT_PATH
          git reset --hard
          git pull

      - name: Restart Service
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          sudo systemctl restart lemonbot.service
