name: Deploy LemonBot Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Repository
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          cd $LEMONBOT_PATH
          git reset --hard
          git clean -fd
          git pull origin main

      - name: Build and Deploy Docs
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          cd docs
          npm install
          npm run docs:build
          ls .vitepress/dist/
          sudo rm -rf /var/www/html/*
          sudo cp -r .vitepress/dist/* /var/www/html/
          
      - name: Restart Nginx Service
        run: |
          sudo systemctl reload nginx.service
