name: Deploy LemonBot Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Repository
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          cd $LEMONBOT_PATH
          git reset --hard
          git clean -fd
          git pull origin main

      - name: Build Docs
        run: |
          cd docs
          npm ci
          npm run docs:build

      - name: Deploy Docs
        env:
          LEMONBOT_PATH: ${{ secrets.LEMONBOT_PATH }}
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r $LEMONBOT_PATH/docs/.vitepress/dist/. /var/www/html/

      - name: Restart Nginx Service
        run: |
          sudo systemctl reload nginx.service
